### ISSUE TITLE
Eval == evil

### ISSUE THREAD

**Issue by Hellowlol** [mancuniancol/script.magnetic.uhdbits-mc#1]
Execute a random string grabbed from random website is insane. There has to be a better way to handle this.

**Comment by mancuniancol** [comment]
I don't understand. What are you reporting?

**Comment by Hellowlol** [comment]
Im referring to https://github.com/mancuniancol/script.magnetic.uhdbits-mc/blob/master/main.py#L32 plus every other in line you use eval.

**Comment by mancuniancol** [comment]
OK, I understand your concern. But, I am trying to give to the user an easy way to modify the parsing if the webpage change or he wants to use a proxy page which has little changes. 

My idea was to add a new section in the settings to easy configure the parsing without modify the code. The majority of people don't know python. 

It is still work in progress , I need to write the documention. 

But, if you check well the code. The eval only calls search methods from ehp module. If you use something else it will crash. 

I don't see any problem of security. But, if you give me an concrete example that you can run something different that search method. Please, let me know. 
.

**Comment by Hellowlol** [comment]
Well say that the value of magnet_search is ```import;subprocess;subprocess.call(["sudo", "-rm", "/"])``` The python will start deleting your entire hdd.

One solution might be to write helpers to parse the response.
```
def maybe_int(s):
  try:
    i = int(s)
    if i > 0:
      return i
    else:
      return ''
  except ValueError:
    return ''
```

**Comment by mancuniancol** [comment]
But, the user has to write down in the first place?

**Comment by mancuniancol** [comment]
I think that if someone wants to run a malicious code using the providers.  He will just change the providers code.

To be honest, I don't believe that it will be like it.

But, if you want to collaborate doing the helpers.  I will add them.  Please, do the pull request.

**Comment by mancuniancol** [comment]
I've rechecked the code and everything from external page, it is converted as ehp entity which doesn't allow to run anything the way you suggest.  The only "hole" will be if the user write directly that code in the settings.  But, it doesn't stop it to do it directly in the python code???

Again, I open to add your contribution.

**Comment by Hellowlol** [comment]
I havnt checked what html does but i assume parses the html. Ill play alittle with it.
